version: "3"

services:
  app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.helloworld.rule=Host(`calzado.ddns.net`)"
      - "traefik.http.routers.helloworld.entrypoints=web"    
    ports:
      - "3000:3000"
    command: npm start
